CREATE TABLE hset_values(
    field_key BIGINT UNSIGNED NOT NULL,
    ordinal INT UNSIGNED NOT NULL,
    value VARBINARY(29500) NOT NULL,
    PRIMARY KEY (field_key, ordinal) USING HASH,
    FOREIGN KEY (field_key) REFERENCES hset_fields(field_key) ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE NDB,
CHARSET = latin1 COMMENT = "NDB_TABLE=PARTITION_BALANCE=RP_BY_LDM_X_8";
