CREATE TABLE hset_keys(
    redis_key VARBINARY(3000) NOT NULL,
    redis_key_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (redis_key) USING HASH,
    UNIQUE KEY (redis_key_id) USING HASH
) ENGINE NDB,
COMMENT = "NDB_TABLE=PARTITION_BALANCE=RP_BY_LDM_X_8";
